# Generated by Django 4.0.10 on 2023-11-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_amount_transaction_paid_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sub_level',
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(max_length=10),
        ),
    ]
