# Generated by Django 4.0.10 on 2023-11-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_student_class_type_remove_student_dept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='monthly',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
